consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Loginresponse:
    description: After login response (default view)
    example:
      code: Mollitia sequi.
      message: Consequatur quisquam omnis magnam.
      secret_key: Cupiditate ut deleniti ea ratione eum recusandae.
      status: 8.2882973e+18
    properties:
      code:
        description: Response code
        example: Mollitia sequi.
        type: string
      message:
        description: Response Message
        example: Consequatur quisquam omnis magnam.
        type: string
      secret_key:
        description: Secret key
        example: Cupiditate ut deleniti ea ratione eum recusandae.
        type: string
      status:
        description: Error Code
        example: 8.2882973e+18
        format: int64
        type: integer
    required:
    - code
    - message
    - status
    - secret_key
    title: 'Mediatype identifier: application/vnd.loginresponse; view=default'
    type: object
  UserPayload:
    description: User data payload
    example:
      UserEmail: Id dolorem mollitia vitae aut.
      UserId: 7.453676e+18
      UserName: Reiciendis sed molestiae aut quia.
    properties:
      UserEmail:
        description: User Email
        example: Id dolorem mollitia vitae aut.
        type: string
      UserId:
        description: User Id
        example: 7.453676e+18
        format: int64
        type: integer
      UserName:
        description: User Name
        example: Reiciendis sed molestiae aut quia.
        type: string
    required:
    - UserId
    - UserName
    - UserEmail
    title: UserPayload
    type: object
  Usercommonresponse:
    description: This will be a common response for most the user end points (default
      view)
    example:
      code: Hic mollitia porro omnis nostrum perspiciatis atque.
      message: Distinctio consequuntur.
      status: 7.2622083e+18
    properties:
      code:
        description: Response code
        example: Hic mollitia porro omnis nostrum perspiciatis atque.
        type: string
      message:
        description: Response Message
        example: Distinctio consequuntur.
        type: string
      status:
        description: Error Code
        example: 7.2622083e+18
        format: int64
        type: integer
    required:
    - code
    - message
    - status
    title: 'Mediatype identifier: application/vnd.usercommonresponse; view=default'
    type: object
  Userdataresponse:
    description: This will be response when user/info endpoint called (default view)
    example:
      code: Repellat commodi voluptas sed numquam.
      data:
        UserEmail: Id dolorem mollitia vitae aut.
        UserId: 7.453676e+18
        UserName: Reiciendis sed molestiae aut quia.
      message: Fugit a doloremque provident.
      status: 2.2904754e+18
    properties:
      code:
        description: Response code
        example: Repellat commodi voluptas sed numquam.
        type: string
      data:
        $ref: '#/definitions/UserPayload'
      message:
        description: Response Message
        example: Fugit a doloremque provident.
        type: string
      status:
        description: Error Code
        example: 2.2904754e+18
        format: int64
        type: integer
    required:
    - code
    - message
    - status
    - data
    title: 'Mediatype identifier: application/vnd.userdataresponse; view=default'
    type: object
info:
  title: goaAPIKeyUserAuth
  version: ""
paths:
  /user/info:
    get:
      description: This action is secure with the api_key scheme
      operationId: user#info
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Userdataresponse'
        "401":
          description: Unauthorized
      security:
      - api_key: []
      summary: info user
      tags:
      - user
  /user/login:
    post:
      description: This action does not require auth
      operationId: user#login
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Loginresponse'
        "401":
          description: Unauthorized
      summary: login user
      tags:
      - user
  /user/logout:
    get:
      description: This action is secure with the api_key scheme
      operationId: user#logout
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Usercommonresponse'
        "401":
          description: Unauthorized
      security:
      - api_key: []
      summary: logout user
      tags:
      - user
  /user/register:
    post:
      description: This endpoint will be used to register a user
      operationId: user#register
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Usercommonresponse'
      summary: register user
      tags:
      - user
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  Unauthorized:
    description: Unauthorized
securityDefinitions:
  api_key:
    in: header
    name: secret-key
    type: apiKey
swagger: "2.0"
